### PR TITLE
Updating buweb to v0.83.0

### PR DESCRIPTION
**Pull request by halloffame**
Using the older version is causing faculty departments to get dropped from the index on save which is removing them from the department section of the faculty page.

### CODE REVIEW

**Comment by halloffame** [comment]
Relates to https://github.com/biola/profile-publisher/pull/155

**Comment by halloffame** [comment]
I traced the problem back to v0.71.0 of buweb. That is when the tests started failing.

**Comment by halloffame** [comment]
Hmm, probably has to do with this commit https://github.com/biola/buweb-content-models/commit/c4112aa78cc5ef1fce31bdc31c6bff982ac9f5f8

**Comment by rift137** [comment]
:+1:

**Pull request merged**
