### PR TITLE
added personal fields to person

### PR DESCRIPTION
**Pull request by matthewl20**

### CODE REVIEW

**Comment by halloffame** [comment]
@jesilz Who should be able to edit these fields? As the policy is currently written, any user can edit their own `personal_phone`, `personal_email`, `personal_website`, should it be left that way?

**Comment by halloffame** [comment]
@matthewl20 sorry, I didn't realize the personal website field is only getting used on the Talbot site. So that it is not confusing for people, can you change it so that only admins can edit this field? Thanks.

**Comment by rift137** [comment]
This needs a buweb content models bump

**Comment by matthewl20** [comment]
This field has been deprecated in favor of adding it to BioEditions.

**Pull request closed without merging**
